name: avataaar_image_2
description: Fork of Flutter wrapper widget for Avataaars API allowing to generate and display avatar images.
version: 2.0.0-dev.2
homepage: https://github.com/Albert-Jan/avataaar-image-2/

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0-nullsafety
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
